name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  format:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: VirtusLab/scala-cli-setup@v1
      - run: scala-cli fmt . --check

  test:
    runs-on: ubuntu-latest
    needs: format
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: VirtusLab/scala-cli-setup@v1
      with:
        power: true
    - name: Test
      run: scala-cli test . --cross --require-tests --suppress-experimental-feature-warning

  publish:
    needs:
      - test
      - format
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: VirtusLab/scala-cli-setup@v1
      with:
        power: true
    - name: Release
      run: scala-cli publish . --cross --suppress-experimental-feature-warning
      env:
        PUBLISH_USER: ${{ secrets.SONATYPE_USERNAME }}
        PUBLISH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        PUBLISH_SECRET_KEY: ${{ secrets.PGP_SECRET }}
        PUBLISH_SECRET_KEY_PASSWORD: ${{ secrets.PGP_PASSPHRASE }}
